import { randomUUID } from "crypto";
import { hashPassword } from "./password";
import type { Database } from "./types";

function ts(offsetDays = 0) {
  return new Date(Date.now() - offsetDays * 86400000).toISOString();
}

export function createSeedDatabase(): Database {
  const passwordHash = hashPassword("demo1234");

  const managerId = randomUUID();
  const buyer1 = randomUUID();
  const buyer2 = randomUUID();
  const buyer3 = randomUUID();
  const buyer4 = randomUUID();
  const seller1 = randomUUID();
  const seller2 = randomUUID();
  const seller3 = randomUUID();

  const assetIds = Array.from({ length: 8 }, () => randomUUID());

  return {
    users: [
      {
        id: managerId,
        email: "manager@n5deal.demo",
        passwordHash,
        name: "Alex Morgan",
        role: "MANAGER",
        status: "ACTIVE",
        company: "N5Deal Platform",
        createdAt: ts(30),
        updatedAt: ts(1),
      },
      {
        id: buyer1,
        email: "buyer@n5deal.demo",
        passwordHash,
        name: "Elena Voss",
        role: "BUYER",
        status: "ACTIVE",
        company: "Nordic Capital Partners",
        createdAt: ts(28),
        updatedAt: ts(2),
      },
      {
        id: buyer2,
        email: "buyer2@n5deal.demo",
        passwordHash,
        name: "Marcus Chen",
        role: "BUYER",
        status: "ACTIVE",
        company: "Pacific Digital Ventures",
        createdAt: ts(27),
        updatedAt: ts(2),
      },
      {
        id: buyer3,
        email: "buyer3@n5deal.demo",
        passwordHash,
        name: "Sofia Alvarez",
        role: "BUYER",
        status: "ACTIVE",
        company: "Iberia Fintech Fund",
        createdAt: ts(26),
        updatedAt: ts(3),
      },
      {
        id: buyer4,
        email: "buyer4@n5deal.demo",
        passwordHash,
        name: "James Okonkwo",
        role: "BUYER",
        status: "ACTIVE",
        company: "Atlas Holdings",
        createdAt: ts(25),
        updatedAt: ts(3),
      },
      {
        id: seller1,
        email: "seller@n5deal.demo",
        passwordHash,
        name: "Viktor Radek",
        role: "SELLER",
        status: "ACTIVE",
        company: "Baltic Pay Group",
        createdAt: ts(24),
        updatedAt: ts(1),
      },
      {
        id: seller2,
        email: "seller2@n5deal.demo",
        passwordHash,
        name: "Nina Patel",
        role: "SELLER",
        status: "ACTIVE",
        company: "ChainLedger Ltd",
        createdAt: ts(23),
        updatedAt: ts(1),
      },
      {
        id: seller3,
        email: "seller3@n5deal.demo",
        passwordHash,
        name: "Omar Haddad",
        role: "SELLER",
        status: "ACTIVE",
        company: "Gulf Shelf Structures",
        createdAt: ts(22),
        updatedAt: ts(4),
      },
    ],
    buyerProfiles: [
      {
        id: randomUUID(),
        userId: buyer1,
        headline: "Family office acquiring licensed EMI / payments assets",
        interests:
          "Looking for regulated payment institutions and EMI licenses in EU jurisdictions. Prefer assets with live customer base and clean compliance history.",
        preferredCategories: "EMI,Payments,Fintech",
        preferredJurisdictions: "Lithuania,Estonia,Cyprus,Malta",
        budgetMin: 500000,
        budgetMax: 5000000,
        ticketNote: "Can move quickly with exclusivity",
        verified: true,
        requiresBanking: true,
        requiresPassporting: true,
        timelineWeeks: 16,
        servicesNeeded: "e-money,SEPA,merchant acquiring",
        createdAt: ts(28),
        updatedAt: ts(2),
      },
      {
        id: randomUUID(),
        userId: buyer2,
        headline: "Strategic buyer for crypto & blockchain infrastructure",
        interests:
          "Seeking crypto exchanges, VASP licenses, and blockchain infrastructure companies with revenue traction in APAC or EU.",
        preferredCategories: "Crypto,VASP,Blockchain",
        preferredJurisdictions: "Singapore,Hong Kong,Estonia,Dubai",
        budgetMin: 1000000,
        budgetMax: 15000000,
        ticketNote: "Strategic + financial hybrid",
        verified: true,
        requiresBanking: false,
        requiresPassporting: false,
        timelineWeeks: 24,
        servicesNeeded: "custody,OTC,exchange",
        createdAt: ts(27),
        updatedAt: ts(2),
      },
      {
        id: randomUUID(),
        userId: buyer3,
        headline: "Growth fund targeting neobanks and lending platforms",
        interests:
          "Interested in consumer neobanks, digital lending, and BNPL platforms with >€2M ARR and EU passporting potential.",
        preferredCategories: "Neobank,Lending,BNPL",
        preferredJurisdictions: "Spain,Portugal,Germany,Netherlands",
        budgetMin: 2000000,
        budgetMax: 20000000,
        ticketNote: null,
        verified: false,
        requiresBanking: true,
        requiresPassporting: true,
        timelineWeeks: 20,
        servicesNeeded: "consumer accounts,lending,BNPL",
        createdAt: ts(26),
        updatedAt: ts(3),
      },
      {
        id: randomUUID(),
        userId: buyer4,
        headline: "Corporate M&A — banking licenses & shelf companies",
        interests:
          "Acquiring banking licenses, shelf companies, and ready-made regulated entities for market entry across EMEA.",
        preferredCategories: "Banking,License,Shelf Company",
        preferredJurisdictions: "UK,UAE,Mauritius,Cayman",
        budgetMin: 250000,
        budgetMax: 3000000,
        ticketNote: null,
        verified: true,
        requiresBanking: false,
        requiresPassporting: false,
        timelineWeeks: 12,
        servicesNeeded: "market entry,corporate vehicle",
        createdAt: ts(25),
        updatedAt: ts(3),
      },
    ],
    sellerProfiles: [
      {
        id: randomUUID(),
        userId: seller1,
        companyName: "Baltic Pay Group",
        bio: "Operator of a licensed EMI in Lithuania with EU passporting. Building and exiting regulated fintech since 2016.",
        website: "https://example.com/baltic-pay",
        verified: true,
        createdAt: ts(24),
        updatedAt: ts(1),
      },
      {
        id: randomUUID(),
        userId: seller2,
        companyName: "ChainLedger Ltd",
        bio: "Crypto infrastructure and VASP-licensed custody provider. Seeking strategic exit after 5 years of growth.",
        website: "https://example.com/chainledger",
        verified: true,
        createdAt: ts(23),
        updatedAt: ts(1),
      },
      {
        id: randomUUID(),
        userId: seller3,
        companyName: "Gulf Shelf Structures",
        bio: "Specialist in ready-made corporate and licensed structures across UAE and offshore jurisdictions.",
        website: null,
        verified: false,
        createdAt: ts(22),
        updatedAt: ts(4),
      },
    ],
    assets: [
      {
        id: assetIds[0],
        sellerId: seller1,
        title: "Lithuanian EMI with EU Passporting",
        summary: "Fully operational EMI license holder with SEPA access and 12,000 active merchants.",
        description:
          "Regulated Electronic Money Institution based in Vilnius. Holds a valid EMI license from the Bank of Lithuania with passporting rights across the EEA. Current stack includes core ledger, KYC/AML pipeline, and merchant onboarding. Clean audit history for the last 3 years. Seller open to share sale or asset carve-out of the license entity.",
        category: "EMI",
        jurisdiction: "Lithuania",
        licenseType: "EMI",
        askingPrice: 2800000,
        currency: "EUR",
        annualRevenue: 1900000,
        employees: 28,
        dealReadiness: "READY",
        status: "PUBLISHED",
        tags: "payments,sepa,emi,regulated",
        bankingStatus: "ACTIVE",
        hasComplianceOfficer: true,
        hasLocalDirector: true,
        hasPassporting: true,
        entityType: "OPERATIONAL",
        changeOfControlNotes:
          "BoL change-of-control notification typically 30–60 days; share deal preferred. No material conditions from existing banking partners expected.",
        servicesInScope: "e-money,SEPA,merchant acquiring,KYC/AML",
        regulator: "Bank of Lithuania",
        createdAt: ts(20),
        updatedAt: ts(1),
      },
      {
        id: assetIds[1],
        sellerId: seller1,
        title: "Payment Gateway SaaS — Baltics",
        summary: "B2B payment orchestration SaaS with recurring revenue and white-label clients.",
        description:
          "Payment gateway and orchestration layer serving PSPs and marketplaces across the Baltics and Nordics. ARR ~€1.1M with 85% gross margin. Ideal bolt-on for a payments group. No own license — operates via partner EMI.",
        category: "Payments",
        jurisdiction: "Estonia",
        licenseType: "Partner EMI",
        askingPrice: 4500000,
        currency: "EUR",
        annualRevenue: 1100000,
        employees: 18,
        dealReadiness: "READY",
        status: "PUBLISHED",
        tags: "saas,payments,b2b,recurring",
        bankingStatus: "IN_PROGRESS",
        hasComplianceOfficer: false,
        hasLocalDirector: true,
        hasPassporting: false,
        entityType: "OPERATIONAL",
        changeOfControlNotes: "Asset/share sale; customer contracts assignable with notice.",
        servicesInScope: "payment orchestration,white-label gateway",
        regulator: null,
        createdAt: ts(19),
        updatedAt: ts(2),
      },
      {
        id: assetIds[2],
        sellerId: seller2,
        title: "EU VASP Crypto Custody Platform",
        summary: "Estonian VASP with institutional custody product and MiCA-ready roadmap.",
        description:
          "Licensed Virtual Asset Service Provider offering cold/warm custody for institutions. ~€800k ARR, growing 60% YoY. Roadmap includes MiCA CASP application.",
        category: "Crypto",
        jurisdiction: "Estonia",
        licenseType: "VASP",
        askingPrice: 6200000,
        currency: "EUR",
        annualRevenue: 800000,
        employees: 22,
        dealReadiness: "URGENT",
        status: "PUBLISHED",
        tags: "crypto,custody,vasp,mica",
        bankingStatus: "ACTIVE",
        hasComplianceOfficer: true,
        hasLocalDirector: true,
        hasPassporting: false,
        entityType: "OPERATIONAL",
        changeOfControlNotes:
          "FIU notification on control change; MiCA transition plan included in data room.",
        servicesInScope: "custody,exchange,OTC",
        regulator: "Estonian FIU",
        createdAt: ts(18),
        updatedAt: ts(1),
      },
      {
        id: assetIds[3],
        sellerId: seller2,
        title: "Crypto OTC Desk & Brokerage",
        summary: "Singapore-based OTC desk with institutional clients and brokerage license path.",
        description:
          "OTC trading desk focused on large-ticket crypto trades for family offices and funds. Strong relationships in APAC.",
        category: "Crypto",
        jurisdiction: "Singapore",
        licenseType: "Brokerage (in progress)",
        askingPrice: 3500000,
        currency: "EUR",
        annualRevenue: 2100000,
        employees: 14,
        dealReadiness: "EXPLORING",
        status: "PUBLISHED",
        tags: "crypto,otc,asia,institutional",
        bankingStatus: "IN_PROGRESS",
        hasComplianceOfficer: true,
        hasLocalDirector: false,
        hasPassporting: false,
        entityType: "OPERATIONAL",
        changeOfControlNotes: "License application transfer subject to MAS discussion.",
        servicesInScope: "OTC,brokerage",
        regulator: "MAS (application)",
        createdAt: ts(17),
        updatedAt: ts(2),
      },
      {
        id: assetIds[4],
        sellerId: seller3,
        title: "UAE Shelf Company — DIFC Ready",
        summary: "Clean shelf company in DIFC with banking relationships ready for activation.",
        description:
          "Dormant but fully incorporated DIFC entity with registered office and initial banking introductions. Suitable for fintech market entry into MENA.",
        category: "Shelf Company",
        jurisdiction: "UAE",
        licenseType: "Corporate",
        askingPrice: 185000,
        currency: "EUR",
        annualRevenue: null,
        employees: 0,
        dealReadiness: "READY",
        status: "PUBLISHED",
        tags: "shelf,difc,uae,market-entry",
        bankingStatus: "IN_PROGRESS",
        hasComplianceOfficer: false,
        hasLocalDirector: true,
        hasPassporting: false,
        entityType: "SHELL",
        changeOfControlNotes: "Share transfer via DIFC Registrar; banking intros transferable.",
        servicesInScope: "corporate vehicle,market entry",
        regulator: "DIFC Registrar",
        createdAt: ts(16),
        updatedAt: ts(3),
      },
      {
        id: assetIds[5],
        sellerId: seller3,
        title: "UK EMI Application Vehicle",
        summary: "UK company with advanced EMI application dossier for FCA submission.",
        description:
          "Purpose-built vehicle with prepared regulatory application materials for UK EMI authorization. Includes policies, capital plan, and key hire pipeline.",
        category: "License",
        jurisdiction: "UK",
        licenseType: "EMI (application)",
        askingPrice: 420000,
        currency: "EUR",
        annualRevenue: null,
        employees: 3,
        dealReadiness: "READY",
        status: "PUBLISHED",
        tags: "emi,uk,fca,license",
        bankingStatus: "NONE",
        hasComplianceOfficer: false,
        hasLocalDirector: true,
        hasPassporting: false,
        entityType: "APPLICATION",
        changeOfControlNotes:
          "Buyer must be acceptable to FCA; application ownership transfer negotiated case-by-case.",
        servicesInScope: "e-money (planned)",
        regulator: "FCA",
        createdAt: ts(15),
        updatedAt: ts(3),
      },
      {
        id: assetIds[6],
        sellerId: seller1,
        title: "Consumer Neobank — Soft Launch",
        summary: "EU neobank soft-launched with e-money partner, 45k waitlist users.",
        description:
          "Consumer-facing neobank brand with modern app, partnered e-money stack, and strong waitlist. Seeking acquisition by a licensed group.",
        category: "Neobank",
        jurisdiction: "Germany",
        licenseType: "Partner EMI",
        askingPrice: 1800000,
        currency: "EUR",
        annualRevenue: 120000,
        employees: 11,
        dealReadiness: "EXPLORING",
        status: "PUBLISHED",
        tags: "neobank,consumer,germany,fintech",
        bankingStatus: "NONE",
        hasComplianceOfficer: false,
        hasLocalDirector: false,
        hasPassporting: false,
        entityType: "OPERATIONAL",
        changeOfControlNotes: "Brand + tech asset deal; partner EMI contract novation required.",
        servicesInScope: "consumer accounts,cards",
        regulator: null,
        createdAt: ts(14),
        updatedAt: ts(2),
      },
      {
        id: assetIds[7],
        sellerId: seller2,
        title: "Digital Lending Platform (BNPL)",
        summary: "BNPL / installment lending platform with merchant network in Southern Europe.",
        description:
          "Technology and merchant contracts for a BNPL product. Risk models, underwriting engine, and integrations included.",
        category: "BNPL",
        jurisdiction: "Spain",
        licenseType: "Credit intermediary",
        askingPrice: 2700000,
        currency: "EUR",
        annualRevenue: 950000,
        employees: 16,
        dealReadiness: "READY",
        status: "PUBLISHED",
        tags: "bnpl,lending,spain,merchants",
        bankingStatus: "ACTIVE",
        hasComplianceOfficer: true,
        hasLocalDirector: true,
        hasPassporting: false,
        entityType: "OPERATIONAL",
        changeOfControlNotes: "Credit intermediary registration update with Bank of Spain.",
        servicesInScope: "BNPL,lending,merchant network",
        regulator: "Bank of Spain",
        createdAt: ts(13),
        updatedAt: ts(1),
      },
    ],
    messages: [
      {
        id: randomUUID(),
        fromUserId: buyer1,
        toUserId: seller1,
        assetId: assetIds[0],
        subject: "Interest in Lithuanian EMI",
        body: "Hello Viktor — we are evaluating your EMI asset for a strategic acquisition. Could we schedule an intro call under NDA?",
        read: false,
        createdAt: ts(2),
      },
      {
        id: randomUUID(),
        fromUserId: seller2,
        toUserId: buyer2,
        assetId: assetIds[2],
        subject: "Match for your crypto mandate",
        body: "Hi Marcus — your buyer profile aligns with our VASP custody platform. Happy to share a teaser deck.",
        read: true,
        createdAt: ts(3),
      },
    ],
  };
}
